from enum import Enum

class RoleEnum(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    WHITE_LABEL = "WHITE_LABEL"
    MASTER_DISTRIBUTOR = "MASTER_DISTRIBUTOR"
    DISTRIBUTOR = "DISTRIBUTOR"
    RETAILER = "RETAILER"
    CUSTOMER = "CUSTOMER"
